# Student.create(email: 'nnnnnnn.0627@gmail.com', password: 'Happylife0627', grade: 3)
# Group.create(id: 1, name: 'サークル1')
# Connection.create(student_id: 1, group_id: 1)
Group.create(id: 2, name: 'パリピ')
Connection.create(student_id: 11, group_id:  2)
